include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - test

.run-reframe:
  stage: test
  tags: ['clariden-login-baremetal']
  variables:
    SLURM_TIMELIMIT: 5
  variables:
    GIT_STRATEGY: fetch
  script:    
    - rm -fr rfm_venv
    - python3 -m venv rfm_venv
    - source rfm_venv/bin/activate
    - pip install reframe-hpc
    - reframe --version
    # - git checkout alpsjg
    - git log --pretty=oneline -n2
    # - git clone -b alpsjg https://github.com/eth-cscs/cscs-reframe-tests.git cscs-reframe-tests.git
    # - ls -r config/*
    - echo UENV=$UENV
    - echo RFM_TEST=$RFM_TEST
    - echo RFM_HTTPJSON_URL=$RFM_HTTPJSON_URL
    - reframe -C config/cscs.py
      --performance-report
      --system=clariden:nvgpu
      --skip-prgenv-check -n UENV
      -c $RFM_TEST
      --report-junit=reframe_report.xml
      -r
    - deactivate
  artifacts:
    when: always
    paths:
    - reframe_report.xml
    reports:
      junit: reframe_report.xml

.run-reframe-clariden:
  extends: .run-reframe
  variables:
    STACK_SYSTEM: clariden

run-reframe-clariden-a100:
  extends: .run-reframe-clariden
  variables:
    SLURM_PARTITION: nvgpu
    UENV: '/iopsstor/scratch/cscs/piccinal/qe/jfrog/store.squashfs'
    RFM_TEST: 'checks/apps/quantumespresso/quantumespresso_check.py'
    # RFM_HTTPJSON_URL: 'http://log.cscs.ch:31311/reframe'
    # https://jfrog.svc.cscs.ch/artifactory/alps-uenv/build/1019353665/hohgant/quantumespresso-a100/store.squashfs
    # /user-environment/linux-sles15-zen3/nvhpc-22.11/quantum-espresso-7.1-vrlplseqnykcxh6jrppbkpknybxkpcvr/
    # UENV=... ~/R -c checks/apps/quantumespresso/quantumespresso_check.py --system clariden:nvgpu -r --skip-prgenv-check -n UENV
